import fs from "node:fs";
import net from "node:net";
import path from "node:path";
import { spawnSync } from "node:child_process";

export const ROOT_DIR = process.cwd();
export const LOCAL_BYPASS_USER_ID = "did:dev:local-user";
export const LOCAL_BYPASS_TOKEN = "dev-bypass";
export const LOCAL_HOSTS = new Set(["localhost", "127.0.0.1", "::1", "[::1]"]);

export function usage(message) {
  console.log(message.trim());
}

export function loadRootDevConfig() {
  const candidates = [
    path.join(ROOT_DIR, ".env.development.local"),
    path.join(ROOT_DIR, ".env.development"),
    path.join(ROOT_DIR, "env.development.local"),
    path.join(ROOT_DIR, "env.development"),
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      return {
        path: candidate,
        values: parseDotEnv(fs.readFileSync(candidate, "utf8")),
      };
    }
  }

  throw new Error(
    "Missing .env.development.local or .env.development. Copy .env.development.example first."
  );
}

export function parseDotEnv(text) {
  const values = {};

  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const separator = line.indexOf("=");
    if (separator === -1) continue;

    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    values[key] = value;
  }

  return values;
}

export function toEnvFile(entries) {
  const lines = [
    "# Generated by scripts/dev/generate-env.mjs",
    "# Do not edit by hand. Update .env.development.local and regenerate.",
    "",
  ];

  for (const [key, value] of Object.entries(entries)) {
    if (value === undefined) continue;
    lines.push(`${key}=${escapeEnvValue(value)}`);
  }

  lines.push("");
  return lines.join("\n");
}

export function writeEnvFile(relativePath, entries) {
  const target = path.join(ROOT_DIR, relativePath);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, toEnvFile(entries), "utf8");
}

export function requireValues(values, keys) {
  const missing = keys.filter((key) => !values[key]);
  if (missing.length > 0) {
    throw new Error(`Missing required values: ${missing.join(", ")}`);
  }
}

export function isTruthy(value) {
  return String(value ?? "")
    .trim()
    .toLowerCase() === "true";
}

export function runCommand(command, args, options = {}) {
  return spawnSync(command, args, {
    cwd: ROOT_DIR,
    encoding: "utf8",
    ...options,
  });
}

export function commandExists(command, args = ["--version"]) {
  const result = runCommand(command, args);
  return result.status === 0;
}

export function portStatus(port) {
  return new Promise((resolve) => {
    const server = net.createServer();

    server.once("error", (error) => {
      if (error && typeof error === "object" && "code" in error) {
        resolve(error.code === "EADDRINUSE" ? "busy" : "error");
        return;
      }
      resolve("error");
    });
    server.once("listening", () => {
      server.close(() => resolve("free"));
    });

    server.listen({ port, host: "127.0.0.1", exclusive: true });
  });
}

export function parseSupabaseEnvOutput(output) {
  return parseDotEnv(output);
}

export function pickFirst(env, candidates) {
  for (const key of candidates) {
    if (env[key]) return env[key];
  }
  return "";
}

export function printSection(title) {
  console.log(`\n== ${title} ==`);
}

function escapeEnvValue(value) {
  const stringValue = String(value ?? "");
  if (stringValue === "") return '""';
  if (/[\s#"']/u.test(stringValue)) {
    return JSON.stringify(stringValue);
  }
  return stringValue;
}
