-- =============================================================================
-- Migration 014: Seed Genre Boilerplates
-- =============================================================================
-- Populates genre_boilerplates with 6 game genres.
-- Each includes shared score atoms + genre-specific starter atoms.
-- =============================================================================

-- ─── Hex Grid Turn-Based Strategy ────────────────────────────────────────────

INSERT INTO genre_boilerplates (slug, display_name, description, atoms_json, externals, template_prompts) VALUES
('hex-grid-tbs', 'Hex Grid Strategy', 'Hex grid with turn-based gameplay — place units, move them, attack enemies.',
'[
  {"name":"create_scene","type":"core","description":"Initialize Three.js scene, camera, renderer, and lighting","code":"function create_scene() {\n  const canvas = document.getElementById(''game-canvas'');\n  const scene = new THREE.Scene();\n  scene.background = new THREE.Color(0x1a1a2e);\n  const camera = new THREE.PerspectiveCamera(60, canvas.clientWidth / canvas.clientHeight, 0.1, 1000);\n  camera.position.set(0, 15, 10);\n  camera.lookAt(0, 0, 0);\n  const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });\n  renderer.setSize(canvas.clientWidth, canvas.clientHeight);\n  const light = new THREE.DirectionalLight(0xffffff, 1);\n  light.position.set(5, 10, 5);\n  scene.add(light);\n  scene.add(new THREE.AmbientLight(0x404040));\n  return { scene, camera, renderer };\n}","inputs":[],"outputs":[{"name":"scene","type":"string"},{"name":"camera","type":"string"},{"name":"renderer","type":"string"}],"dependencies":[]},
  {"name":"hex_grid_create","type":"feature","description":"Create a hexagonal grid of tiles as 3D meshes","code":"function hex_grid_create(radius, scene_ref) {\n  const tiles = [];\n  const size = 1;\n  const geo = new THREE.CylinderGeometry(size, size, 0.2, 6);\n  for (let q = -radius; q <= radius; q++) {\n    for (let r = Math.max(-radius, -q - radius); r <= Math.min(radius, -q + radius); r++) {\n      const x = size * (3/2 * q);\n      const z = size * (Math.sqrt(3)/2 * q + Math.sqrt(3) * r);\n      const mat = new THREE.MeshStandardMaterial({ color: 0x2d6a4f });\n      const mesh = new THREE.Mesh(geo, mat);\n      mesh.position.set(x, 0, z);\n      mesh.userData = { q, r, occupied: false };\n      tiles.push(mesh);\n    }\n  }\n  return JSON.stringify(tiles.length);\n}","inputs":[{"name":"radius","type":"number"},{"name":"scene_ref","type":"string"}],"outputs":[{"name":"tile_count","type":"string"}],"dependencies":[]},
  {"name":"turn_manager","type":"feature","description":"Manage turn state between players","code":"function turn_manager(action, current_player) {\n  if (!window._turnState) window._turnState = { player: 1, turnCount: 0 };\n  if (action === ''end_turn'') {\n    window._turnState.player = window._turnState.player === 1 ? 2 : 1;\n    window._turnState.turnCount++;\n  }\n  return JSON.stringify(window._turnState);\n}","inputs":[{"name":"action","type":"string"},{"name":"current_player","type":"number"}],"outputs":[{"name":"state","type":"string"}],"dependencies":[]},
  {"name":"score_tracker","type":"util","description":"Track and report game score via postMessage","code":"function score_tracker(points, action) {\n  if (!window._score) window._score = 0;\n  if (action === ''add'') window._score += points;\n  if (action === ''reset'') window._score = 0;\n  window.parent.postMessage({ type: ''SCORE_UPDATE'', score: window._score }, ''*'');\n  return window._score;\n}","inputs":[{"name":"points","type":"number"},{"name":"action","type":"string"}],"outputs":[{"name":"score","type":"number"}],"dependencies":[]},
  {"name":"game_loop","type":"core","description":"Main game loop with animation frame","code":"function game_loop() {\n  const { scene, camera, renderer } = create_scene();\n  function animate() {\n    requestAnimationFrame(animate);\n    window.GAME.tick();\n    renderer.render(scene, camera);\n  }\n  animate();\n}","inputs":[],"outputs":[],"dependencies":["create_scene"]}
]'::jsonb,
ARRAY['three_js'],
ARRAY['Add units that can move between hex tiles', 'Create an attack system with damage and health', 'Add fog of war that reveals as units explore']);

-- ─── Side-Scroller 2D/3D ────────────────────────────────────────────────────

INSERT INTO genre_boilerplates (slug, display_name, description, atoms_json, externals, template_prompts) VALUES
('side-scroller-2d-3d', 'Side-Scroller', '2D sprites in 3D space — classic platformer with jumping, running, and collectibles.',
'[
  {"name":"create_scene","type":"core","description":"Initialize Three.js scene with orthographic-like perspective for side-scrolling","code":"function create_scene() {\n  const canvas = document.getElementById(''game-canvas'');\n  const scene = new THREE.Scene();\n  scene.background = new THREE.Color(0x87ceeb);\n  const aspect = canvas.clientWidth / canvas.clientHeight;\n  const camera = new THREE.PerspectiveCamera(45, aspect, 0.1, 1000);\n  camera.position.set(0, 3, 15);\n  camera.lookAt(0, 3, 0);\n  const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });\n  renderer.setSize(canvas.clientWidth, canvas.clientHeight);\n  const light = new THREE.DirectionalLight(0xffffff, 1);\n  light.position.set(5, 10, 5);\n  scene.add(light);\n  scene.add(new THREE.AmbientLight(0x606060));\n  return { scene, camera, renderer };\n}","inputs":[],"outputs":[{"name":"scene","type":"string"},{"name":"camera","type":"string"},{"name":"renderer","type":"string"}],"dependencies":[]},
  {"name":"platform_physics","type":"feature","description":"Simple gravity and ground collision for side-scroller","code":"function platform_physics(pos_y, vel_y, ground_y, dt) {\n  const gravity = -20;\n  let newVelY = vel_y + gravity * dt;\n  let newPosY = pos_y + newVelY * dt;\n  let grounded = false;\n  if (newPosY <= ground_y) {\n    newPosY = ground_y;\n    newVelY = 0;\n    grounded = true;\n  }\n  return JSON.stringify({ y: newPosY, vy: newVelY, grounded });\n}","inputs":[{"name":"pos_y","type":"number"},{"name":"vel_y","type":"number"},{"name":"ground_y","type":"number"},{"name":"dt","type":"number"}],"outputs":[{"name":"result","type":"string"}],"dependencies":[]},
  {"name":"camera_follow","type":"feature","description":"Smoothly follow the player horizontally","code":"function camera_follow(camera_x, target_x, dt) {\n  const speed = 5;\n  const newX = camera_x + (target_x - camera_x) * speed * dt;\n  return newX;\n}","inputs":[{"name":"camera_x","type":"number"},{"name":"target_x","type":"number"},{"name":"dt","type":"number"}],"outputs":[{"name":"new_x","type":"number"}],"dependencies":[]},
  {"name":"score_tracker","type":"util","description":"Track and report game score via postMessage","code":"function score_tracker(points, action) {\n  if (!window._score) window._score = 0;\n  if (action === ''add'') window._score += points;\n  if (action === ''reset'') window._score = 0;\n  window.parent.postMessage({ type: ''SCORE_UPDATE'', score: window._score }, ''*'');\n  return window._score;\n}","inputs":[{"name":"points","type":"number"},{"name":"action","type":"string"}],"outputs":[{"name":"score","type":"number"}],"dependencies":[]},
  {"name":"game_loop","type":"core","description":"Main game loop for side-scroller","code":"function game_loop() {\n  const { scene, camera, renderer } = create_scene();\n  function animate() {\n    requestAnimationFrame(animate);\n    window.GAME.tick();\n    const dt = window.GAME.time.delta;\n    renderer.render(scene, camera);\n  }\n  animate();\n}","inputs":[],"outputs":[],"dependencies":["create_scene"]}
]'::jsonb,
ARRAY['three_js'],
ARRAY['Add a player character that can run and jump', 'Create platforms and obstacles to navigate', 'Add collectible coins that increase the score']);

-- ─── 3D Roguelike Deckbuilder ────────────────────────────────────────────────

INSERT INTO genre_boilerplates (slug, display_name, description, atoms_json, externals, template_prompts) VALUES
('3d-roguelike-deckbuilder', 'Roguelike Deckbuilder', 'Card-based combat with procedural room generation — draw cards, play them, defeat enemies.',
'[
  {"name":"create_scene","type":"core","description":"Initialize Three.js scene for top-down roguelike view","code":"function create_scene() {\n  const canvas = document.getElementById(''game-canvas'');\n  const scene = new THREE.Scene();\n  scene.background = new THREE.Color(0x0a0a1a);\n  const camera = new THREE.PerspectiveCamera(50, canvas.clientWidth / canvas.clientHeight, 0.1, 1000);\n  camera.position.set(0, 12, 8);\n  camera.lookAt(0, 0, 0);\n  const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });\n  renderer.setSize(canvas.clientWidth, canvas.clientHeight);\n  scene.add(new THREE.DirectionalLight(0xffffff, 0.8));\n  scene.add(new THREE.AmbientLight(0x404060));\n  return { scene, camera, renderer };\n}","inputs":[],"outputs":[{"name":"scene","type":"string"},{"name":"camera","type":"string"},{"name":"renderer","type":"string"}],"dependencies":[]},
  {"name":"deck_manager","type":"feature","description":"Manage a deck of cards — draw, discard, shuffle","code":"function deck_manager(action, card_name) {\n  if (!window._deck) window._deck = { draw: [], hand: [], discard: [] };\n  const d = window._deck;\n  if (action === ''init'') {\n    d.draw = [''Strike'',''Strike'',''Strike'',''Defend'',''Defend'',''Heal''];\n    d.hand = []; d.discard = [];\n    for (let i = d.draw.length - 1; i > 0; i--) { const j = Math.floor(Math.random()*(i+1)); [d.draw[i],d.draw[j]] = [d.draw[j],d.draw[i]]; }\n  }\n  if (action === ''draw'' && d.draw.length > 0) d.hand.push(d.draw.pop());\n  if (action === ''play'' && card_name) { d.hand = d.hand.filter(c => c !== card_name); d.discard.push(card_name); }\n  return JSON.stringify(d);\n}","inputs":[{"name":"action","type":"string"},{"name":"card_name","type":"string"}],"outputs":[{"name":"state","type":"string"}],"dependencies":[]},
  {"name":"room_generator","type":"feature","description":"Generate a simple room layout with walls and floor","code":"function room_generator(width, depth) {\n  const tiles = [];\n  for (let x = 0; x < width; x++) {\n    for (let z = 0; z < depth; z++) {\n      const isWall = x === 0 || x === width-1 || z === 0 || z === depth-1;\n      tiles.push({ x, z, type: isWall ? ''wall'' : ''floor'' });\n    }\n  }\n  return JSON.stringify(tiles);\n}","inputs":[{"name":"width","type":"number"},{"name":"depth","type":"number"}],"outputs":[{"name":"tiles","type":"string"}],"dependencies":[]},
  {"name":"score_tracker","type":"util","description":"Track and report game score via postMessage","code":"function score_tracker(points, action) {\n  if (!window._score) window._score = 0;\n  if (action === ''add'') window._score += points;\n  if (action === ''reset'') window._score = 0;\n  window.parent.postMessage({ type: ''SCORE_UPDATE'', score: window._score }, ''*'');\n  return window._score;\n}","inputs":[{"name":"points","type":"number"},{"name":"action","type":"string"}],"outputs":[{"name":"score","type":"number"}],"dependencies":[]},
  {"name":"game_loop","type":"core","description":"Main game loop for roguelike","code":"function game_loop() {\n  const { scene, camera, renderer } = create_scene();\n  deck_manager(''init'', '''');\n  function animate() {\n    requestAnimationFrame(animate);\n    window.GAME.tick();\n    renderer.render(scene, camera);\n  }\n  animate();\n}","inputs":[],"outputs":[],"dependencies":["create_scene","deck_manager"]}
]'::jsonb,
ARRAY['three_js'],
ARRAY['Add enemies that take damage from card plays', 'Create a card reward screen after clearing a room', 'Add a minimap showing explored rooms']);

-- ─── Arena Dogfighter ────────────────────────────────────────────────────────

INSERT INTO genre_boilerplates (slug, display_name, description, atoms_json, externals, template_prompts) VALUES
('arena-dogfighter', 'Arena Dogfighter', 'Flight physics and aerial combat — pilot a ship, shoot projectiles, dodge enemies.',
'[
  {"name":"create_scene","type":"core","description":"Initialize Three.js scene for aerial combat","code":"function create_scene() {\n  const canvas = document.getElementById(''game-canvas'');\n  const scene = new THREE.Scene();\n  scene.background = new THREE.Color(0x0f0f2e);\n  scene.fog = new THREE.Fog(0x0f0f2e, 50, 200);\n  const camera = new THREE.PerspectiveCamera(75, canvas.clientWidth / canvas.clientHeight, 0.1, 1000);\n  camera.position.set(0, 5, 15);\n  const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });\n  renderer.setSize(canvas.clientWidth, canvas.clientHeight);\n  scene.add(new THREE.DirectionalLight(0xffffff, 1));\n  scene.add(new THREE.AmbientLight(0x303050));\n  return { scene, camera, renderer };\n}","inputs":[],"outputs":[{"name":"scene","type":"string"},{"name":"camera","type":"string"},{"name":"renderer","type":"string"}],"dependencies":[]},
  {"name":"flight_controls","type":"feature","description":"Handle flight physics — pitch, yaw, roll, thrust","code":"function flight_controls(vx, vy, vz, dt) {\n  const keys = window.GAME.inputs.keys;\n  const thrust = 10;\n  let ax = 0, ay = 0, az = 0;\n  if (keys[''KeyW'']) az -= thrust;\n  if (keys[''KeyS'']) az += thrust;\n  if (keys[''KeyA'']) ax -= thrust;\n  if (keys[''KeyD'']) ax += thrust;\n  if (keys[''Space'']) ay += thrust;\n  if (keys[''ShiftLeft'']) ay -= thrust;\n  const drag = 0.98;\n  const nvx = (vx + ax * dt) * drag;\n  const nvy = (vy + ay * dt) * drag;\n  const nvz = (vz + az * dt) * drag;\n  return JSON.stringify({ vx: nvx, vy: nvy, vz: nvz });\n}","inputs":[{"name":"vx","type":"number"},{"name":"vy","type":"number"},{"name":"vz","type":"number"},{"name":"dt","type":"number"}],"outputs":[{"name":"velocity","type":"string"}],"dependencies":[]},
  {"name":"projectile_system","type":"feature","description":"Manage projectile creation and movement","code":"function projectile_system(action, x, y, z) {\n  if (!window._projectiles) window._projectiles = [];\n  if (action === ''fire'') {\n    window._projectiles.push({ x, y, z, vz: -50, life: 2 });\n  }\n  if (action === ''update'') {\n    const dt = window.GAME.time.delta;\n    window._projectiles = window._projectiles.filter(p => {\n      p.z += p.vz * dt;\n      p.life -= dt;\n      return p.life > 0;\n    });\n  }\n  return JSON.stringify(window._projectiles.length);\n}","inputs":[{"name":"action","type":"string"},{"name":"x","type":"number"},{"name":"y","type":"number"},{"name":"z","type":"number"}],"outputs":[{"name":"count","type":"string"}],"dependencies":[]},
  {"name":"score_tracker","type":"util","description":"Track and report game score via postMessage","code":"function score_tracker(points, action) {\n  if (!window._score) window._score = 0;\n  if (action === ''add'') window._score += points;\n  if (action === ''reset'') window._score = 0;\n  window.parent.postMessage({ type: ''SCORE_UPDATE'', score: window._score }, ''*'');\n  return window._score;\n}","inputs":[{"name":"points","type":"number"},{"name":"action","type":"string"}],"outputs":[{"name":"score","type":"number"}],"dependencies":[]},
  {"name":"game_loop","type":"core","description":"Main game loop for dogfighter","code":"function game_loop() {\n  const { scene, camera, renderer } = create_scene();\n  function animate() {\n    requestAnimationFrame(animate);\n    window.GAME.tick();\n    const dt = window.GAME.time.delta;\n    projectile_system(''update'', 0, 0, 0);\n    renderer.render(scene, camera);\n  }\n  animate();\n}","inputs":[],"outputs":[],"dependencies":["create_scene","projectile_system"]}
]'::jsonb,
ARRAY['three_js'],
ARRAY['Add a player ship with WASD flight controls', 'Create enemy ships that chase and shoot at the player', 'Add health bars and explosion effects on destruction']);

-- ─── Base Builder ────────────────────────────────────────────────────────────

INSERT INTO genre_boilerplates (slug, display_name, description, atoms_json, externals, template_prompts) VALUES
('base-builder', 'Base Builder', 'Grid-based building with resource management — place structures, gather resources, expand.',
'[
  {"name":"create_scene","type":"core","description":"Initialize Three.js scene for top-down base building","code":"function create_scene() {\n  const canvas = document.getElementById(''game-canvas'');\n  const scene = new THREE.Scene();\n  scene.background = new THREE.Color(0x2a4a2a);\n  const camera = new THREE.PerspectiveCamera(50, canvas.clientWidth / canvas.clientHeight, 0.1, 1000);\n  camera.position.set(0, 20, 15);\n  camera.lookAt(0, 0, 0);\n  const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });\n  renderer.setSize(canvas.clientWidth, canvas.clientHeight);\n  scene.add(new THREE.DirectionalLight(0xffffff, 1));\n  scene.add(new THREE.AmbientLight(0x505050));\n  return { scene, camera, renderer };\n}","inputs":[],"outputs":[{"name":"scene","type":"string"},{"name":"camera","type":"string"},{"name":"renderer","type":"string"}],"dependencies":[]},
  {"name":"grid_placement","type":"feature","description":"Grid-based building placement system","code":"function grid_placement(grid_x, grid_z, building_type) {\n  if (!window._grid) window._grid = {};\n  const key = grid_x + '','' + grid_z;\n  if (window._grid[key]) return JSON.stringify({ error: ''occupied'' });\n  window._grid[key] = { type: building_type, x: grid_x, z: grid_z };\n  return JSON.stringify({ placed: building_type, x: grid_x, z: grid_z });\n}","inputs":[{"name":"grid_x","type":"number"},{"name":"grid_z","type":"number"},{"name":"building_type","type":"string"}],"outputs":[{"name":"result","type":"string"}],"dependencies":[]},
  {"name":"resource_manager","type":"feature","description":"Track resources — wood, stone, gold","code":"function resource_manager(action, resource, amount) {\n  if (!window._resources) window._resources = { wood: 100, stone: 50, gold: 25 };\n  const r = window._resources;\n  if (action === ''add'') r[resource] = (r[resource] || 0) + amount;\n  if (action === ''spend'') {\n    if ((r[resource] || 0) < amount) return JSON.stringify({ error: ''not_enough'' });\n    r[resource] -= amount;\n  }\n  return JSON.stringify(r);\n}","inputs":[{"name":"action","type":"string"},{"name":"resource","type":"string"},{"name":"amount","type":"number"}],"outputs":[{"name":"state","type":"string"}],"dependencies":[]},
  {"name":"score_tracker","type":"util","description":"Track and report game score via postMessage","code":"function score_tracker(points, action) {\n  if (!window._score) window._score = 0;\n  if (action === ''add'') window._score += points;\n  if (action === ''reset'') window._score = 0;\n  window.parent.postMessage({ type: ''SCORE_UPDATE'', score: window._score }, ''*'');\n  return window._score;\n}","inputs":[{"name":"points","type":"number"},{"name":"action","type":"string"}],"outputs":[{"name":"score","type":"number"}],"dependencies":[]},
  {"name":"game_loop","type":"core","description":"Main game loop for base builder","code":"function game_loop() {\n  const { scene, camera, renderer } = create_scene();\n  function animate() {\n    requestAnimationFrame(animate);\n    window.GAME.tick();\n    renderer.render(scene, camera);\n  }\n  animate();\n}","inputs":[],"outputs":[],"dependencies":["create_scene"]}
]'::jsonb,
ARRAY['three_js'],
ARRAY['Add buildings that can be placed on the grid', 'Create a resource gathering system with workers', 'Add enemy waves that attack the base']);

-- ─── Custom (Empty Scaffold) ─────────────────────────────────────────────────

INSERT INTO genre_boilerplates (slug, display_name, description, atoms_json, externals, template_prompts) VALUES
('custom', 'Custom', 'Start from scratch with a blank Three.js canvas — build anything you can imagine.',
'[
  {"name":"create_scene","type":"core","description":"Initialize Three.js scene, camera, and renderer","code":"function create_scene() {\n  const canvas = document.getElementById(''game-canvas'');\n  const scene = new THREE.Scene();\n  scene.background = new THREE.Color(0x111111);\n  const camera = new THREE.PerspectiveCamera(60, canvas.clientWidth / canvas.clientHeight, 0.1, 1000);\n  camera.position.set(0, 5, 10);\n  camera.lookAt(0, 0, 0);\n  const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });\n  renderer.setSize(canvas.clientWidth, canvas.clientHeight);\n  scene.add(new THREE.DirectionalLight(0xffffff, 1));\n  scene.add(new THREE.AmbientLight(0x404040));\n  return { scene, camera, renderer };\n}","inputs":[],"outputs":[{"name":"scene","type":"string"},{"name":"camera","type":"string"},{"name":"renderer","type":"string"}],"dependencies":[]},
  {"name":"score_tracker","type":"util","description":"Track and report game score via postMessage","code":"function score_tracker(points, action) {\n  if (!window._score) window._score = 0;\n  if (action === ''add'') window._score += points;\n  if (action === ''reset'') window._score = 0;\n  window.parent.postMessage({ type: ''SCORE_UPDATE'', score: window._score }, ''*'');\n  return window._score;\n}","inputs":[{"name":"points","type":"number"},{"name":"action","type":"string"}],"outputs":[{"name":"score","type":"number"}],"dependencies":[]},
  {"name":"game_loop","type":"core","description":"Main game loop with animation frame","code":"function game_loop() {\n  const { scene, camera, renderer } = create_scene();\n  function animate() {\n    requestAnimationFrame(animate);\n    window.GAME.tick();\n    const dt = window.GAME.time.delta;\n    renderer.render(scene, camera);\n  }\n  animate();\n}","inputs":[],"outputs":[],"dependencies":["create_scene"]}
]'::jsonb,
ARRAY['three_js'],
ARRAY['Create a spinning cube with colors', 'Build a simple first-person camera with WASD movement', 'Add interactive objects that respond to mouse clicks']);
